AWSTemplateFormatVersion: 2010-09-09
Description: Application_Layer Template

Parameters:
  Namebase:
    Type: String
    Default: lecture13
    
  RDSpassword:
    Description: Input RDS Password 
    Type: String
    Default: ''
    NoEcho: true
  
Resources:
# パラメーター
  MyDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties: 
      Description: MySQL Parameter Group
      DBParameterGroupName: !Sub $lecture13-db-parametergroup-CFn
      Family: mysql8.0
      Tags:
        - Key: Name
          Value: !Sub $lecture13-db-parametergroup-CFn
# rds作成
  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
    # パブリックアクセス
      StorageType: gp2
      AllocatedStorage : 20
      PubliclyAccessible: false
    # インスタンス識別子
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      DBInstanceClass: db.t3.micro
      Port: 3306
      BackupRetentionPeriod: 7
      MasterUsername: admin
      MasterUserPassword: !Ref RDSpassword
      DBInstanceIdentifier: !Sub ${Namebase}-rds
      DBName: RDS10
      DBParameterGroupName: !Ref MyDBParameterGroup
      Engine: MySQL
      EngineVersion: 8.0.35
      DBSubnetGroupName: !Ref RDSSubnetgroup
      VPCSecurityGroups:
        - !ImportValue ${Namebase}-SecurityGroupRDS
        
  # サブネットグループ
  RDSSubnetgroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: for RDS
      DBSubnetGroupName: SampleRDSSubnetgroup
      SubnetIds:
        - !ImportValue lecture13-PrivateSubnet1id
        - !ImportValue lecture13-PrivateSubnet2id  
