version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-cloudformation: orbss/aws-cloudformation@0.1.6
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  execute-cloudformation:
    executor: aws-cloudformation/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - aws-cloudformation/deploy:
          stack-name: "lecture13-network-stack"
          template-file-path: "cloudformation/network.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-security-stack"
          template-file-path: "cloudformation/security.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-app1-stack"
          template-file-path: "cloudformation/application1.yml"
          capabilities: CAPABILITY_NAMED_IAM
      - aws-cloudformation/deploy:
          stack-name: "lecture13-app2-stack"
          template-file-path: "cloudformation/application2.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-app3-stack"
          template-file-path: "cloudformation/application3.yml"
          capabilities: CAPABILITY_NAMED_IAM
      - aws-cloudformation/deploy:
          stack-name: "lecture13-app4-stack"
          template-file-path: "cloudformation/application4.yml"
          
  execute-ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - SHA256:1L4djQiuMIWSJwXsMSIW9HJqz7IjPsQpARLqhU6H+o0
      - ansible-playbook/install:
          version: 2.9.23
      - run:
          name: Install Ansible
          command: pip install ansible
      - run:
          name: Create required directories
          command: mkdir -p ~/.ansible/collections/ansible_collections
      - run:
          name: Verify directories
          command: ls -la ~/.ansible/collections/
      - run:
          name: Install Ansible Galaxy Collections
          command: |
            ansible-galaxy collection install amazon.aws
            ansible-galaxy collection install community.mysql
            ansible-galaxy collection install community.aws
      - run:
          name: Install Ansible community.aws collection
          command: ansible-galaxy collection install community.aws
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: -u ec2-user -i ansible/inventory --private-key ~/.ssh/authorized_key

workflows:
  lecture13-workflow:
    jobs:
      - execute-cloudformation
      - execute-ansible:
          requires:
            - execute-cloudformation
