# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1


orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-cloudformation: orbss/aws-cloudformation@0.1.6
  ansible-playbook: orbss/ansible-playbook@0.0.5
 

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  execute-cloudformation:
    executor: aws-cloudformation/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - aws-cloudformation/deploy:
          stack-name: "lecture13-network-stack"
          template-file-path: "cloudformation/network.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-security-stack"
          template-file-path: "cloudformation/security.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-app1-stack"
          template-file-path: "cloudformation/application1.yml"
          capabilities: CAPABILITY_NAMED_IAM
      - aws-cloudformation/deploy:
          stack-name: "lecture13-app2-stack"
          template-file-path: "cloudformation/application2.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-app3-stack"
          template-file-path: "cloudformation/application3.yml"
          capabilities: CAPABILITY_NAMED_IAM
      - aws-cloudformation/deploy:
          stack-name: "lecture13-app4-stack"
          template-file-path: "cloudformation/application4.yml"
          
  get-variables-from-cfn:
    executor: aws-cli/default
    steps:
      - checkout
      - run:  # 環境変数の設定
          name: set environment variables in env_vars.sh
          command: |
            RDSResourceId=$(aws cloudformation describe-stack-resources --stack-name '<< pipeline.parameters.stack-name >>-rds' --query "StackResources[?ResourceType=='AWS::RDS::DBInstance'].PhysicalResourceId" --output text)
            echo export RDSResourceId=$RDSResourceId >> env_vars.sh   # Having separated export from input, due to avoiding "empty $RDSResourceId" error
            echo export RDSEndPoint=$(aws rds describe-db-instances --db-instance-identifier $RDSResourceId --query DBInstances[].Endpoint.Address --output text) >> env_vars.sh
            echo export RDSUser=$(aws rds describe-db-instances --db-instance-identifier $RDSResourceId --query DBInstances[].MasterUsername[] --output text) >> env_vars.sh
            S3_bucket_name=$(aws cloudformation describe-stacks --stack-name application-layer-stack --query "Stacks[0].Outputs[?OutputKey=='S3BucketName'].OutputValue" --output text)
            echo export S3_bucket_name=$S3_bucket_name >> env_vars.sh
            ALB_DNS=$(aws cloudformation describe-stacks --region ap-northeast-1 --stack-name lecture13-app3-stack --query "Stacks[0].Outputs[?OutputKey=='ALBDnsName'].OutputValue" --output text)
            echo export ALB_DNS=$ALB_DNS >> env_vars.sh
            
      - persist_to_workspace:
          root: .
          paths:
            - env_vars.sh
            
  execute-ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - SHA256:1L4djQiuMIWSJwXsMSIW9HJqz7IjPsQpARLqhU6H+o0
      - ansible-playbook/install:
          version: 2.9.23
      - run:
          name: Install Ansible
          command: pip install ansible
      - run:
          name: Create required directories
          command: |
            mkdir -p ~/.ansible/collections/ansible_collections
      - run:
          name: Verify directories
          command: |
            ls -la ~/.ansible/collections/
      - run:
          name: Install Ansible Galaxy Collections
          command: ansible-galaxy collection install amazon.aws
      - run:
          name: Install Ansible Galaxy Collections
          command: ansible-galaxy collection install community.mysql
      - run:
          name: Use Environment Variable
          command: |
            source .env_var
            echo $RDSResourceId
            echo $DNS_NAME
            echo $S3_bucket_name
      - run:
          name: Replacing environment variables in Sed
          command: |
            source .env_var
            sed -i "s/$DNS_NAME/${DNS_NAME}/g" ansible/playbook.yml
            sed -i "s/$S3_bucket_name/${$S3_bucket_name}/g" ansible/playbook.yml
            cat ansible/playbook.yml
          no_output_timeout: 30m
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: -u ec2-user -i ansible/inventory --private-key ~/.ssh/authorized_key
      
          
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  lecture13-workflow:
    jobs:
      - execute-cloudformation
      - execute-ansible:
          requires:
            - execute-cloudformation
  
# This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
