# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1


orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-cloudformation: orbss/aws-cloudformation@0.1.6
 

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  execute-cloudformation:
    executor: aws-cloudformation/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - aws-cloudformation/deploy:
          stack-name: "lecture13-network-stack"
          template-file-path: "cloudformation/network.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-security-stack"
          template-file-path: "cloudformation/security.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-app1-stack"
          template-file-path: "cloudformation/application1.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-app2-stack"
          template-file-path: "cloudformation/application2.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-app3-stack"
          template-file-path: "cloudformation/application3.yml"
      - aws-cloudformation/deploy:
          stack-name: "lecture13-app4-stack"
          template-file-path: "cloudformation/application4.yml"
          


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  lecture13-workflow:
    jobs:
      - execute-cloudformation
# This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - say-hello